name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: release
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
      
      - name: Install dependencies
        run: npm install
      
      - name: Build Android
        run: eas build --platform android --non-interactive
      
      - name: Build iOS
        run: eas build --platform ios --non-interactive
      
      - name: Upload builds to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.apk
            build/*.aab
            build/*.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
